### ISSUE TITLE
How would you save the predicted slots?

### ISSUE THREAD

**Issue by IssamLaradji** [untitled-ai/slot_attention#1]
Great code! I like how it trains on CLEVR out of the box. I would like to save the predicted images like below. Could you help me find out where I could add the `Image.save` function to get this output? Thanks!
![image](https://user-images.githubusercontent.com/3382128/108508611-121ee500-728a-11eb-84ce-2ddc52809902.png)

**Comment by brydenfogelman** [comment]
Thanks! Check out the code here: https://github.com/untitled-ai/slot_attention/blob/a4b1967eaffb43446cfc2730612f92cb2bb82846/slot_attention/method.py#L28

Calling `sample_images` should return a tensor that you can pass to `to_pil_image` (see here: https://pytorch.org/docs/stable/torchvision/transforms.html?highlight=to_pil_image#torchvision.transforms.functional.to_pil_image) to get a PIL image you can call `Image.save` on (PS the labels were added after the fact).

Hope that helps!
