### ISSUE TITLE
reconstruct result

### ISSUE THREAD

**Issue by tqace** [untitled-ai/slot_attention#2]
awesome code！ I wonder why the shape reconstruction performance doesn't match the tensorflow version？ Is it because of the hyper parameters？

**Comment by brydenfogelman** [comment]
I tried to as closely as possible copy the hyperparameters from the original authors.

I think the biggest issue is the runtime, the original authors trained their model for 5 days of wall clock time. Would be worth it to train it for that long at some point but it's a bit expensive and time-consuming at the moment.

**Comment by tqace** [comment]
thanks, i found that they croped out a 192*192 patch and resized it
