### ISSUE TITLE
Is it a bug that `slot_mu` and `slot_log_sigma` is not updated in training?

### ISSUE THREAD

**Issue by Wuziyi616** [untitled-ai/slot_attention#8]
Hi. Thank you for opening source this wonderful implementation! I have a small question about a code and think it might be a bug.

In [these lines]( https://github.com/untitled-ai/slot_attention/blob/2656866bda1958ddab68f11584031462e558de86/slot_attention/model.py#L41-L48), you define `slot_mu` and `slot_log_sigma` using `register_buffer`. If I understand correctly, tensors created via `register_buffer` won't be updated during training (see [here](https://discuss.pytorch.org/t/what-is-the-difference-between-register-buffer-and-register-parameter-of-nn-module/32723) for reference). I also check my trained checkpoints, these two values are indeed the same throughout the training process.

Also, in other slot-attention implementations, they define them as trainable parameters (see [PyTorch one](https://github.com/lucidrains/slot-attention/blob/4224f9d3100469a99d73f0ef02a545cb39fbb8fb/slot_attention/slot_attention.py#L13-L16) and [the official one](https://github.com/google-research/google-research/blob/40ec00915276ac1e6d86db7a30598917b08b6535/slot_attention/model.py#L47-L57)). So I just wonder if this is a bug or intentional behavior?

Update: I didn't observe much performance difference using trainable or fixed mu+sigma. That's very interesting.

**Comment by joshalbrecht** [comment]
I think you are correct that this was a bug, and not an intentional change. Thanks for flagging!

**Comment by Wuziyi616** [comment]
Indeed you're right. Actually I run experiments after fixing it, and the performance difference is very small (<5%). So I think the learned slot initialization distribution is not very important.
